FROM python:3.11-slim                           
                                                  
  WORKDIR /workspace                              
                                                  
  COPY requirements.txt .                         
  RUN pip install -q -r requirements.txt          
                                                  
  COPY . .                                        
                                                  
  CMD ["python3", "scripts/indexer.py","--config", "config/config.yaml"]   