// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

// ============================================
// Enum Types (extracted for token efficiency)
// ============================================

export type ActivityAction = 'created' | 'updated' | 'deleted' | 'status_changed' | 'assigned' | 'commented' | 'attachment_added' | 'attachment_removed';
export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'revision_requested';
export type AttachmentEntityType = 'task' | 'project' | 'phase' | 'profile' | 'subcontractor';
export type BudgetStatus = 'draft' | 'approved' | 'locked';
export type DocumentCategory = 'contracts' | 'permits' | 'drawings' | 'reports' | 'financial' | 'safety' | 'meeting_notes' | 'specifications' | 'general';
export type EstimateStatus = 'draft' | 'reviewed' | 'approved' | 'superseded';
export type ExpenseCategory = 'materials' | 'labor' | 'equipment' | 'permits' | 'transportation' | 'meals' | 'lodging' | 'other';
export type ExtractionMethod = 'labeled' | 'calculated' | 'inferred' | 'manual';
export type ExtractionStage = 'extract_vectors' | 'classify_sheet' | 'detect_scale' | 'detect_elements' | 'detect_rooms' | 'extract_schedules' | 'extract_mep' | 'calculate_quantities' | 'cross_page_reconcile' | 'generate_estimate';
export type JobStatus = 'pending' | 'claimed' | 'processing' | 'completed' | 'failed' | 'dead_letter';
export type MarkerContentType = 'photo' | 'file' | 'note' | 'activity';
export type MaterialCategory = 'lumber' | 'concrete' | 'electrical' | 'plumbing' | 'hvac' | 'roofing' | 'flooring' | 'paint' | 'hardware' | 'tools' | 'fixtures' | 'insulation' | 'drywall' | 'doors_windows' | 'landscaping' | 'other';
export type MemberStatus = 'active' | 'invited' | 'inactive';
export type NotificationType = 'task_assigned' | 'task_completed' | 'task_overdue' | 'task_blocked' | 'project_update' | 'team_invited' | 'mention' | 'system';
export type PhaseStatus = 'not_started' | 'in_progress' | 'completed' | 'on_hold';
export type PhotoCategory = 'site_progress' | 'safety_documentation' | 'permits_approvals' | 'inspection_reports' | 'material_receipts' | 'change_orders' | 'defects_issues' | 'before_after' | 'task_receipts' | 'expense_receipts' | 'general';
export type PlanPageParseStatus = 'pending' | 'parsing' | 'parsed' | 'parse_failed';
export type PlanUploadStatus = 'uploading' | 'processing' | 'ready' | 'failed';
export type ProcurementStatus = 'needed' | 'ordered' | 'delivered' | 'installed';
export type ProjectStatus = 'active' | 'on_hold' | 'completed' | 'archived' | 'planning' | 'in_progress';
export type ProjectType = 'residential' | 'restaurant' | 'cafe' | 'commercial_office' | 'industrial';
export type PurchaserType = 'gc' | 'pm' | 'subcontractor';
export type ReviewStatus = 'pending' | 'accepted' | 'rejected' | 'edited';
export type SpatialMarkerStatus = 'open' | 'in_progress' | 'resolved' | 'closed';
export type SpatialMarkerType = 'issue' | 'note' | 'photo' | 'inspection' | 'rfi' | 'safety' | 'material' | 'progress';
export type SpatialProcessingStatus = 'pending' | 'processing' | 'ready' | 'failed';
export type TakeoffCategory = 'structural' | 'architectural' | 'mechanical' | 'electrical' | 'plumbing' | 'painting' | 'site' | 'general';
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical';
export type TaskStatus = 'todo' | 'in_progress' | 'review' | 'blocked' | 'completed';
export type TradeType = 'general' | 'electrical' | 'plumbing' | 'hvac' | 'carpentry' | 'masonry' | 'roofing' | 'flooring' | 'painting' | 'drywall' | 'concrete' | 'landscaping' | 'demolition' | 'steel_work' | 'glass_glazing' | 'fire_protection' | 'insulation' | 'other' | 'framing';
export type UserRole = 'admin' | 'project_manager' | 'foreman' | 'field_worker' | 'subcontractor' | 'client';

// Re-export generic Enums helper for complex queries
export type { Enums } from '../database.types';