// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Admin Domain Types
// ============================================

// admin_invitations
export type AdminInvitationsRow = Database['public']['Tables']['admin_invitations']['Row'];
export type AdminInvitationsInsert = Database['public']['Tables']['admin_invitations']['Insert'];
export type AdminInvitationsUpdate = Database['public']['Tables']['admin_invitations']['Update'];

// owners
export type OwnersRow = Database['public']['Tables']['owners']['Row'];
export type OwnersInsert = Database['public']['Tables']['owners']['Insert'];
export type OwnersUpdate = Database['public']['Tables']['owners']['Update'];

// team_invitations
export type TeamInvitationsRow = Database['public']['Tables']['team_invitations']['Row'];
export type TeamInvitationsInsert = Database['public']['Tables']['team_invitations']['Insert'];
export type TeamInvitationsUpdate = Database['public']['Tables']['team_invitations']['Update'];

// attachments
export type AttachmentsRow = Database['public']['Tables']['attachments']['Row'];
export type AttachmentsInsert = Database['public']['Tables']['attachments']['Insert'];
export type AttachmentsUpdate = Database['public']['Tables']['attachments']['Update'];

// file_audit_log
export type FileAuditLogRow = Database['public']['Tables']['file_audit_log']['Row'];
export type FileAuditLogInsert = Database['public']['Tables']['file_audit_log']['Insert'];
export type FileAuditLogUpdate = Database['public']['Tables']['file_audit_log']['Update'];
