// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Chat Domain Types
// ============================================

// chat_rooms
export type ChatRoomsRow = Database['public']['Tables']['chat_rooms']['Row'];
export type ChatRoomsInsert = Database['public']['Tables']['chat_rooms']['Insert'];
export type ChatRoomsUpdate = Database['public']['Tables']['chat_rooms']['Update'];

// chat_participants
export type ChatParticipantsRow = Database['public']['Tables']['chat_participants']['Row'];
export type ChatParticipantsInsert = Database['public']['Tables']['chat_participants']['Insert'];
export type ChatParticipantsUpdate = Database['public']['Tables']['chat_participants']['Update'];

// messages
export type MessagesRow = Database['public']['Tables']['messages']['Row'];
export type MessagesInsert = Database['public']['Tables']['messages']['Insert'];
export type MessagesUpdate = Database['public']['Tables']['messages']['Update'];

// message_attachments
export type MessageAttachmentsRow = Database['public']['Tables']['message_attachments']['Row'];
export type MessageAttachmentsInsert = Database['public']['Tables']['message_attachments']['Insert'];
export type MessageAttachmentsUpdate = Database['public']['Tables']['message_attachments']['Update'];

// message_reactions
export type MessageReactionsRow = Database['public']['Tables']['message_reactions']['Row'];
export type MessageReactionsInsert = Database['public']['Tables']['message_reactions']['Insert'];
export type MessageReactionsUpdate = Database['public']['Tables']['message_reactions']['Update'];
