// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Companies Domain Types
// ============================================

// companies
export type CompaniesRow = Database['public']['Tables']['companies']['Row'];
export type CompaniesInsert = Database['public']['Tables']['companies']['Insert'];
export type CompaniesUpdate = Database['public']['Tables']['companies']['Update'];

// company_users
export type CompanyUsersRow = Database['public']['Tables']['company_users']['Row'];
export type CompanyUsersInsert = Database['public']['Tables']['company_users']['Insert'];
export type CompanyUsersUpdate = Database['public']['Tables']['company_users']['Update'];

// company_default_models
export type CompanyDefaultModelsRow = Database['public']['Tables']['company_default_models']['Row'];
export type CompanyDefaultModelsInsert = Database['public']['Tables']['company_default_models']['Insert'];
export type CompanyDefaultModelsUpdate = Database['public']['Tables']['company_default_models']['Update'];

// subcontractors
export type SubcontractorsRow = Database['public']['Tables']['subcontractors']['Row'];
export type SubcontractorsInsert = Database['public']['Tables']['subcontractors']['Insert'];
export type SubcontractorsUpdate = Database['public']['Tables']['subcontractors']['Update'];

// stripe_customers
export type StripeCustomersRow = Database['public']['Tables']['stripe_customers']['Row'];
export type StripeCustomersInsert = Database['public']['Tables']['stripe_customers']['Insert'];
export type StripeCustomersUpdate = Database['public']['Tables']['stripe_customers']['Update'];
