// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Expenses Domain Types
// ============================================

// expenses
export type ExpensesRow = Database['public']['Tables']['expenses']['Row'];
export type ExpensesInsert = Database['public']['Tables']['expenses']['Insert'];
export type ExpensesUpdate = Database['public']['Tables']['expenses']['Update'];

// expense_line_items
export type ExpenseLineItemsRow = Database['public']['Tables']['expense_line_items']['Row'];
export type ExpenseLineItemsInsert = Database['public']['Tables']['expense_line_items']['Insert'];
export type ExpenseLineItemsUpdate = Database['public']['Tables']['expense_line_items']['Update'];
