// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Materials Domain Types
// ============================================

// materials
export type MaterialsRow = Database['public']['Tables']['materials']['Row'];
export type MaterialsInsert = Database['public']['Tables']['materials']['Insert'];
export type MaterialsUpdate = Database['public']['Tables']['materials']['Update'];

// material_assignments
export type MaterialAssignmentsRow = Database['public']['Tables']['material_assignments']['Row'];
export type MaterialAssignmentsInsert = Database['public']['Tables']['material_assignments']['Insert'];
export type MaterialAssignmentsUpdate = Database['public']['Tables']['material_assignments']['Update'];

// material_price_history
export type MaterialPriceHistoryRow = Database['public']['Tables']['material_price_history']['Row'];
export type MaterialPriceHistoryInsert = Database['public']['Tables']['material_price_history']['Insert'];
export type MaterialPriceHistoryUpdate = Database['public']['Tables']['material_price_history']['Update'];

// tracked_materials
export type TrackedMaterialsRow = Database['public']['Tables']['tracked_materials']['Row'];
export type TrackedMaterialsInsert = Database['public']['Tables']['tracked_materials']['Insert'];
export type TrackedMaterialsUpdate = Database['public']['Tables']['tracked_materials']['Update'];
