// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Projects Domain Types
// ============================================

// projects
export type ProjectsRow = Database['public']['Tables']['projects']['Row'];
export type ProjectsInsert = Database['public']['Tables']['projects']['Insert'];
export type ProjectsUpdate = Database['public']['Tables']['projects']['Update'];

// project_files
export type ProjectFilesRow = Database['public']['Tables']['project_files']['Row'];
export type ProjectFilesInsert = Database['public']['Tables']['project_files']['Insert'];
export type ProjectFilesUpdate = Database['public']['Tables']['project_files']['Update'];

// project_phases
export type ProjectPhasesRow = Database['public']['Tables']['project_phases']['Row'];
export type ProjectPhasesInsert = Database['public']['Tables']['project_phases']['Insert'];
export type ProjectPhasesUpdate = Database['public']['Tables']['project_phases']['Update'];

// project_photos
export type ProjectPhotosRow = Database['public']['Tables']['project_photos']['Row'];
export type ProjectPhotosInsert = Database['public']['Tables']['project_photos']['Insert'];
export type ProjectPhotosUpdate = Database['public']['Tables']['project_photos']['Update'];

// project_team
export type ProjectTeamRow = Database['public']['Tables']['project_team']['Row'];
export type ProjectTeamInsert = Database['public']['Tables']['project_team']['Insert'];
export type ProjectTeamUpdate = Database['public']['Tables']['project_team']['Update'];

// project_type_configs
export type ProjectTypeConfigsRow = Database['public']['Tables']['project_type_configs']['Row'];
export type ProjectTypeConfigsInsert = Database['public']['Tables']['project_type_configs']['Insert'];
export type ProjectTypeConfigsUpdate = Database['public']['Tables']['project_type_configs']['Update'];

// phase_templates
export type PhaseTemplatesRow = Database['public']['Tables']['phase_templates']['Row'];
export type PhaseTemplatesInsert = Database['public']['Tables']['phase_templates']['Insert'];
export type PhaseTemplatesUpdate = Database['public']['Tables']['phase_templates']['Update'];
