// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Spatial Domain Types
// ============================================

// spatial_markers
export type SpatialMarkersRow = Database['public']['Tables']['spatial_markers']['Row'];
export type SpatialMarkersInsert = Database['public']['Tables']['spatial_markers']['Insert'];
export type SpatialMarkersUpdate = Database['public']['Tables']['spatial_markers']['Update'];

// marker_content
export type MarkerContentRow = Database['public']['Tables']['marker_content']['Row'];
export type MarkerContentInsert = Database['public']['Tables']['marker_content']['Insert'];
export type MarkerContentUpdate = Database['public']['Tables']['marker_content']['Update'];

// model_elements
export type ModelElementsRow = Database['public']['Tables']['model_elements']['Row'];
export type ModelElementsInsert = Database['public']['Tables']['model_elements']['Insert'];
export type ModelElementsUpdate = Database['public']['Tables']['model_elements']['Update'];

// default_marker_configs
export type DefaultMarkerConfigsRow = Database['public']['Tables']['default_marker_configs']['Row'];
export type DefaultMarkerConfigsInsert = Database['public']['Tables']['default_marker_configs']['Insert'];
export type DefaultMarkerConfigsUpdate = Database['public']['Tables']['default_marker_configs']['Update'];

// projects_3d_models
export type Projects3dModelsRow = Database['public']['Tables']['projects_3d_models']['Row'];
export type Projects3dModelsInsert = Database['public']['Tables']['projects_3d_models']['Insert'];
export type Projects3dModelsUpdate = Database['public']['Tables']['projects_3d_models']['Update'];
