// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Tasks Domain Types
// ============================================

// tasks
export type TasksRow = Database['public']['Tables']['tasks']['Row'];
export type TasksInsert = Database['public']['Tables']['tasks']['Insert'];
export type TasksUpdate = Database['public']['Tables']['tasks']['Update'];

// task_activity
export type TaskActivityRow = Database['public']['Tables']['task_activity']['Row'];
export type TaskActivityInsert = Database['public']['Tables']['task_activity']['Insert'];
export type TaskActivityUpdate = Database['public']['Tables']['task_activity']['Update'];

// task_assignees
export type TaskAssigneesRow = Database['public']['Tables']['task_assignees']['Row'];
export type TaskAssigneesInsert = Database['public']['Tables']['task_assignees']['Insert'];
export type TaskAssigneesUpdate = Database['public']['Tables']['task_assignees']['Update'];

// task_dependencies
export type TaskDependenciesRow = Database['public']['Tables']['task_dependencies']['Row'];
export type TaskDependenciesInsert = Database['public']['Tables']['task_dependencies']['Insert'];
export type TaskDependenciesUpdate = Database['public']['Tables']['task_dependencies']['Update'];

// task_templates
export type TaskTemplatesRow = Database['public']['Tables']['task_templates']['Row'];
export type TaskTemplatesInsert = Database['public']['Tables']['task_templates']['Insert'];
export type TaskTemplatesUpdate = Database['public']['Tables']['task_templates']['Update'];

// task_type_configs
export type TaskTypeConfigsRow = Database['public']['Tables']['task_type_configs']['Row'];
export type TaskTypeConfigsInsert = Database['public']['Tables']['task_type_configs']['Insert'];
export type TaskTypeConfigsUpdate = Database['public']['Tables']['task_type_configs']['Update'];
