// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

import type { Database } from '../../database.types';

// ============================================
// Users Domain Types
// ============================================

// user_profiles
export type UserProfilesRow = Database['public']['Tables']['user_profiles']['Row'];
export type UserProfilesInsert = Database['public']['Tables']['user_profiles']['Insert'];
export type UserProfilesUpdate = Database['public']['Tables']['user_profiles']['Update'];

// notifications
export type NotificationsRow = Database['public']['Tables']['notifications']['Row'];
export type NotificationsInsert = Database['public']['Tables']['notifications']['Insert'];
export type NotificationsUpdate = Database['public']['Tables']['notifications']['Update'];

// push_subscriptions
export type PushSubscriptionsRow = Database['public']['Tables']['push_subscriptions']['Row'];
export type PushSubscriptionsInsert = Database['public']['Tables']['push_subscriptions']['Insert'];
export type PushSubscriptionsUpdate = Database['public']['Tables']['push_subscriptions']['Update'];

// kakao_connections
export type KakaoConnectionsRow = Database['public']['Tables']['kakao_connections']['Row'];
export type KakaoConnectionsInsert = Database['public']['Tables']['kakao_connections']['Insert'];
export type KakaoConnectionsUpdate = Database['public']['Tables']['kakao_connections']['Update'];
