#!/usr/bin/env npx tsx
/**
 * Database Types Generator
 *
 * Parses database.types.ts and generates modular type files to reduce token usage.
 * Run: npx tsx scripts/gen-db-types.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'types/database.types.ts');
const OUTPUT_DIR = path.join(ROOT, 'types/db');

// Domain groupings for tables
const TABLE_GROUPS: Record<string, string[]> = {
  tasks: [
    'tasks',
    'task_activity',
    'task_assignees',
    'task_dependencies',
    'task_templates',
    'task_type_configs',
  ],
  projects: [
    'projects',
    'project_files',
    'project_phases',
    'project_photos',
    'project_team',
    'project_type_configs',
    'phase_templates',
  ],
  expenses: [
    'expenses',
    'expense_line_items',
  ],
  materials: [
    'materials',
    'material_assignments',
    'material_price_history',
    'tracked_materials',
  ],
  spatial: [
    'spatial_markers',
    'marker_content',
    'model_elements',
    'default_marker_configs',
    'projects_3d_models',
  ],
  users: [
    'user_profiles',
    'notifications',
    'push_subscriptions',
    'kakao_connections',
  ],
  chat: [
    'chat_rooms',
    'chat_participants',
    'messages',
    'message_attachments',
    'message_reactions',
  ],
  companies: [
    'companies',
    'company_users',
    'company_default_models',
    'subcontractors',
    'stripe_customers',
  ],
  admin: [
    'admin_invitations',
    'owners',
    'team_invitations',
    'attachments',
    'file_audit_log',
  ],
};

function parseEnums(content: string): Map<string, string[]> {
  const enums = new Map<string, string[]>();

  // Match enum definitions in the Enums: { ... } block
  const enumsBlockMatch = content.match(/Enums:\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/);
  if (!enumsBlockMatch) return enums;

  const enumsBlock = enumsBlockMatch[1];

  // Parse each enum: name: "val1" | "val2" | ...
  const enumRegex = /(\w+):\s*((?:\|?\s*"[^"]+"\s*)+)/g;
  let match;

  while ((match = enumRegex.exec(enumsBlock)) !== null) {
    const enumName = match[1];
    const valuesStr = match[2];
    const values = valuesStr.match(/"([^"]+)"/g)?.map(v => v.replace(/"/g, '')) || [];
    enums.set(enumName, values);
  }

  return enums;
}

function parseTableNames(content: string): string[] {
  const tables: string[] = [];

  // Match table definitions: table_name: { Row: ...
  const tableRegex = /^\s{6}(\w+):\s*\{\s*$/gm;
  let match;

  while ((match = tableRegex.exec(content)) !== null) {
    const tableName = match[1];
    // Exclude functions (they have different structure)
    if (!tableName.startsWith('get_') &&
        !tableName.startsWith('find_') &&
        !tableName.startsWith('acquire_') &&
        !tableName.startsWith('seed_')) {
      tables.push(tableName);
    }
  }

  return tables;
}

function toPascalCase(str: string): string {
  return str.split('_').map(part =>
    part.charAt(0).toUpperCase() + part.slice(1)
  ).join('');
}

function generateEnumsFile(enums: Map<string, string[]>): string {
  const lines = [
    '// Auto-generated by scripts/gen-db-types.ts',
    '// DO NOT EDIT MANUALLY',
    '',
    '// ============================================',
    '// Enum Types (extracted for token efficiency)',
    '// ============================================',
    '',
  ];

  for (const [name, values] of enums) {
    const typeName = toPascalCase(name);
    const valueUnion = values.map(v => `'${v}'`).join(' | ');
    lines.push(`export type ${typeName} = ${valueUnion};`);
  }

  lines.push('');
  lines.push('// Re-export generic Enums helper for complex queries');
  lines.push("export type { Enums } from '../database.types';");

  return lines.join('\n');
}

function generateTableFile(groupName: string, tables: string[]): string {
  const lines = [
    '// Auto-generated by scripts/gen-db-types.ts',
    '// DO NOT EDIT MANUALLY',
    '',
    "import type { Database } from '../../database.types';",
    '',
    `// ============================================`,
    `// ${toPascalCase(groupName)} Domain Types`,
    `// ============================================`,
    '',
  ];

  for (const table of tables) {
    const pascalName = toPascalCase(table);
    lines.push(`// ${table}`);
    lines.push(`export type ${pascalName}Row = Database['public']['Tables']['${table}']['Row'];`);
    lines.push(`export type ${pascalName}Insert = Database['public']['Tables']['${table}']['Insert'];`);
    lines.push(`export type ${pascalName}Update = Database['public']['Tables']['${table}']['Update'];`);
    lines.push('');
  }

  return lines.join('\n');
}

function generateTablesIndexFile(groups: string[]): string {
  const lines = [
    '// Auto-generated by scripts/gen-db-types.ts',
    '// DO NOT EDIT MANUALLY',
    '',
  ];

  for (const group of groups) {
    lines.push(`export * from './${group}';`);
  }

  return lines.join('\n');
}

function generateHelpersFile(): string {
  return `// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

// Re-export helper types from database.types.ts
export type {
  Database,
  Json,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from '../database.types';

// Re-export Constants for runtime enum values
export { Constants } from '../database.types';
`;
}

function generateMainIndexFile(): string {
  return `// Auto-generated by scripts/gen-db-types.ts
// DO NOT EDIT MANUALLY

// Barrel export for all modular types
export * from './enums';
export * from './helpers';
export * from './tables';
`;
}

function main() {
  console.log('🔍 Reading database.types.ts...');
  const content = fs.readFileSync(SOURCE, 'utf-8');

  console.log('📊 Parsing enums...');
  const enums = parseEnums(content);
  console.log(`   Found ${enums.size} enums`);

  console.log('📊 Parsing tables...');
  const tables = parseTableNames(content);
  console.log(`   Found ${tables.length} tables`);

  // Create output directories
  const tablesDir = path.join(OUTPUT_DIR, 'tables');
  fs.mkdirSync(tablesDir, { recursive: true });

  // Generate enums file
  console.log('✍️  Generating enums.ts...');
  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'enums.ts'),
    generateEnumsFile(enums)
  );

  // Generate helpers file
  console.log('✍️  Generating helpers.ts...');
  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'helpers.ts'),
    generateHelpersFile()
  );

  // Generate table files by domain
  const generatedGroups: string[] = [];
  for (const [groupName, groupTables] of Object.entries(TABLE_GROUPS)) {
    // Filter to only include tables that exist
    const existingTables = groupTables.filter(t => tables.includes(t));
    if (existingTables.length === 0) continue;

    console.log(`✍️  Generating tables/${groupName}.ts (${existingTables.length} tables)...`);
    fs.writeFileSync(
      path.join(tablesDir, `${groupName}.ts`),
      generateTableFile(groupName, existingTables)
    );
    generatedGroups.push(groupName);
  }

  // Generate tables index
  console.log('✍️  Generating tables/index.ts...');
  fs.writeFileSync(
    path.join(tablesDir, 'index.ts'),
    generateTablesIndexFile(generatedGroups)
  );

  // Generate main index
  console.log('✍️  Generating index.ts...');
  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'index.ts'),
    generateMainIndexFile()
  );

  console.log('');
  console.log('✅ Generation complete!');
  console.log('');
  console.log('Generated files:');
  console.log('  types/db/');
  console.log('  ├── index.ts');
  console.log('  ├── enums.ts');
  console.log('  ├── helpers.ts');
  console.log('  └── tables/');
  console.log('      ├── index.ts');
  for (const group of generatedGroups) {
    console.log(`      ├── ${group}.ts`);
  }
}

main();
