-- Migration: Create message_attachments table for file and photo sharing
-- Task: 0009 - File & Photo Sharing
-- Description: Enables file/photo uploads in chat with size limits and type restrictions

-- ============================================
-- Create message_attachments table
-- ============================================

CREATE TABLE IF NOT EXISTS public.message_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text NOT NULL,
  file_size integer NOT NULL CHECK (file_size > 0 AND file_size <= 10485760), -- Max 10MB
  thumbnail_url text, -- For images, can be generated by Vercel Blob
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ============================================
-- Comments
-- ============================================

COMMENT ON TABLE public.message_attachments IS
'File and photo attachments for chat messages. Max file size: 10MB. Supported types: images (jpg, png, gif, webp), documents (pdf, doc, docx, xls, xlsx), archives (zip)';

COMMENT ON COLUMN public.message_attachments.file_size IS
'File size in bytes. Maximum allowed: 10485760 (10MB)';

COMMENT ON COLUMN public.message_attachments.thumbnail_url IS
'Thumbnail URL for images. Can be auto-generated by Vercel Blob or manually set.';

-- ============================================
-- Indexes
-- ============================================

CREATE INDEX idx_message_attachments_message_id
ON public.message_attachments(message_id);

CREATE INDEX idx_message_attachments_created_at
ON public.message_attachments(created_at DESC);

-- ============================================
-- RLS Policies
-- ============================================

ALTER TABLE public.message_attachments ENABLE ROW LEVEL SECURITY;

-- Users can view attachments in chat rooms they participate in
CREATE POLICY "Users can view attachments in their chat rooms"
ON public.message_attachments
FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM messages m
    INNER JOIN chat_participants cp ON cp.chat_room_id = m.chat_room_id
    WHERE m.id = message_attachments.message_id
    AND cp.user_id = next_auth.uid()
  )
);

-- Authenticated users can upload attachments to messages in their chat rooms
CREATE POLICY "Users can upload attachments to their messages"
ON public.message_attachments
FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM messages m
    INNER JOIN chat_participants cp ON cp.chat_room_id = m.chat_room_id
    WHERE m.id = message_attachments.message_id
    AND cp.user_id = next_auth.uid()
  )
);

-- Users can delete their own attachments
CREATE POLICY "Users can delete their own attachments"
ON public.message_attachments
FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM messages m
    WHERE m.id = message_attachments.message_id
    AND m.sender_id = next_auth.uid()
  )
);

-- ============================================
-- Triggers
-- ============================================

-- Auto-update updated_at timestamp
CREATE TRIGGER update_message_attachments_updated_at
BEFORE UPDATE ON public.message_attachments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Update message.updated_at when attachment is added/removed
CREATE OR REPLACE FUNCTION update_message_on_attachment_change()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
    UPDATE messages SET updated_at = now() WHERE id = NEW.message_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE messages SET updated_at = now() WHERE id = OLD.message_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_message_attachment_change
AFTER INSERT OR UPDATE OR DELETE ON public.message_attachments
FOR EACH ROW
EXECUTE FUNCTION update_message_on_attachment_change();

-- ============================================
-- Optional: Project attachment sync
-- ============================================

-- For project chat rooms, optionally sync attachments to the main attachments table
-- This allows project files uploaded via chat to appear in project file list
CREATE OR REPLACE FUNCTION sync_project_chat_attachments()
RETURNS TRIGGER AS $$
DECLARE
  v_project_id uuid;
BEGIN
  -- Only process INSERT operations
  IF TG_OP = 'INSERT' THEN
    -- Get project_id from chat_room if this is a project chat
    SELECT cr.project_id INTO v_project_id
    FROM messages m
    INNER JOIN chat_rooms cr ON cr.id = m.chat_room_id
    WHERE m.id = NEW.message_id
    AND cr.type = 'project'
    AND cr.project_id IS NOT NULL;

    -- If this is a project chat, create a corresponding attachments record
    IF v_project_id IS NOT NULL THEN
      INSERT INTO public.attachments (
        entity_type,
        entity_id,
        file_name,
        file_url,
        file_type,
        file_size,
        uploaded_by
      )
      SELECT
        'project'::attachment_entity_type,
        v_project_id,
        NEW.file_name,
        NEW.file_url,
        NEW.file_type,
        NEW.file_size,
        m.sender_id
      FROM messages m
      WHERE m.id = NEW.message_id
      ON CONFLICT DO NOTHING; -- Prevent duplicates if attachment already exists
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Comment out trigger initially - can be enabled later if needed
-- CREATE TRIGGER sync_project_attachments_on_insert
-- AFTER INSERT ON public.message_attachments
-- FOR EACH ROW
-- EXECUTE FUNCTION sync_project_chat_attachments();

COMMENT ON FUNCTION sync_project_chat_attachments() IS
'Optional trigger function to sync chat attachments to project attachments table. Currently disabled. Enable by creating trigger: sync_project_attachments_on_insert';
